{
  "classifiers": [
    "development status :: 5 - production/stable",
    "intended audience :: developers",
    "license :: osi approved :: mit license",
    "natural language :: english",
    "operating system :: os independent",
    "programming language :: python",
    "programming language :: python :: 3",
    "programming language :: python :: 3.10",
    "programming language :: python :: 3.7",
    "programming language :: python :: 3.8",
    "programming language :: python :: 3.9",
    "topic :: internet :: www/http",
    "topic :: software development :: libraries :: python modules",
    "topic :: utilities"
  ],
  "description": "backoff\n=======\n\n.. image:: https://travis-ci.org/litl/backoff.svg\n    :target: https://travis-ci.org/litl/backoff\n.. image:: https://coveralls.io/repos/litl/backoff/badge.svg\n    :target: https://coveralls.io/r/litl/backoff?branch=python-3\n.. image:: https://github.com/litl/backoff/workflows/codeql/badge.svg\n    :target: https://github.com/litl/backoff/actions/workflows/codeql-analysis.yml\n.. image:: https://img.shields.io/pypi/v/backoff.svg\n    :target: https://pypi.python.org/pypi/backoff\n.. image:: https://img.shields.io/github/license/litl/backoff\n    :target: https://github.com/litl/backoff/blob/master/license\n\n**function decoration for backoff and retry**\n\nthis module provides function decorators which can be used to wrap a\nfunction such that it will be retried until some condition is met. it\nis meant to be of use when accessing unreliable resources with the\npotential for intermittent failures i.e. network resources and external\napis. somewhat more generally, it may also be of use for dynamically\npolling resources for externally generated content.\n\ndecorators support both regular functions for synchronous code and\n`asyncio <https://docs.python.org/3/library/asyncio.html>`__'s coroutines\nfor asynchronous code.\n\nexamples\n========\n\nsince kenneth reitz's `requests <http://python-requests.org>`_ module\nhas become a defacto standard for synchronous http clients in python,\nnetworking examples below are written using it, but it is in no way required\nby the backoff module.\n\n@backoff.on_exception\n---------------------\n\nthe ``on_exception`` decorator is used to retry when a specified exception\nis raised. here's an example using exponential backoff when any\n``requests`` exception is raised:\n\n.. code-block:: python\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception)\n    def get_url(url):\n        return requests.get(url)\n\nthe decorator will also accept a tuple of exceptions for cases where\nthe same backoff behavior is desired for more than one exception type:\n\n.. code-block:: python\n\n    @backoff.on_exception(backoff.expo,\n                          (requests.exceptions.timeout,\n                           requests.exceptions.connectionerror))\n    def get_url(url):\n        return requests.get(url)\n\n**give up conditions**\n\noptional keyword arguments can specify conditions under which to give\nup.\n\nthe keyword argument ``max_time`` specifies the maximum amount\nof total time in seconds that can elapse before giving up.\n\n.. code-block:: python\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception,\n                          max_time=60)\n    def get_url(url):\n        return requests.get(url)\n\n\nkeyword argument ``max_tries`` specifies the maximum number of calls\nto make to the target function before giving up.\n\n.. code-block:: python\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception,\n                          max_tries=8,\n                          jitter=none)\n    def get_url(url):\n        return requests.get(url)\n\n\nin some cases the raised exception instance itself may need to be\ninspected in order to determine if it is a retryable condition. the\n``giveup`` keyword arg can be used to specify a function which accepts\nthe exception and returns a truthy value if the exception should not\nbe retried:\n\n.. code-block:: python\n\n    def fatal_code(e):\n        return 400 <= e.response.status_code < 500\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception,\n                          max_time=300,\n                          giveup=fatal_code)\n    def get_url(url):\n        return requests.get(url)\n\nby default, when a give up event occurs, the exception in question is reraised\nand so code calling an `on_exception`-decorated function may still\nneed to do exception handling. this behavior can optionally be disabled\nusing the `raise_on_giveup` keyword argument.\n\nin the code below, `requests.exceptions.requestexception` will not be raised\nwhen giveup occurs. note that the decorated function will return `none` in this\ncase, regardless of the logic in the `on_exception` handler.\n\n.. code-block:: python\n\n    def fatal_code(e):\n        return 400 <= e.response.status_code < 500\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception,\n                          max_time=300,\n                          raise_on_giveup=false,\n                          giveup=fatal_code)\n    def get_url(url):\n        return requests.get(url)\n\nthis is useful for non-mission critical code where you still wish to retry\nthe code inside of `backoff.on_exception` but wish to proceed with execution\neven if all retries fail.\n\n@backoff.on_predicate\n---------------------\n\nthe ``on_predicate`` decorator is used to retry when a particular\ncondition is true of the return value of the target function.  this may\nbe useful when polling a resource for externally generated content.\n\nhere's an example which uses a fibonacci sequence backoff when the\nreturn value of the target function is the empty list:\n\n.. code-block:: python\n\n    @backoff.on_predicate(backoff.fibo, lambda x: x == [], max_value=13)\n    def poll_for_messages(queue):\n        return queue.get()\n\nextra keyword arguments are passed when initializing the\nwait generator, so the ``max_value`` param above is passed as a keyword\narg when initializing the fibo generator.\n\nwhen not specified, the predicate param defaults to the falsey test,\nso the above can more concisely be written:\n\n.. code-block:: python\n\n    @backoff.on_predicate(backoff.fibo, max_value=13)\n    def poll_for_message(queue):\n        return queue.get()\n\nmore simply, a function which continues polling every second until it\ngets a non-falsey result could be defined like like this:\n\n.. code-block:: python\n\n    @backoff.on_predicate(backoff.constant, jitter=none, interval=1)\n    def poll_for_message(queue):\n        return queue.get()\n\nthe jitter is disabled in order to keep the polling frequency fixed.  \n\n@backoff.runtime\n----------------\n\nyou can also use the ``backoff.runtime`` generator to make use of the\nreturn value or thrown exception of the decorated method.\n\nfor example, to use the value in the ``retry-after`` header of the response:\n\n.. code-block:: python\n\n    @backoff.on_predicate(\n        backoff.runtime,\n        predicate=lambda r: r.status_code == 429,\n        value=lambda r: int(r.headers.get(\"retry-after\")),\n        jitter=none,\n    )\n    def get_url():\n        return requests.get(url)\n\njitter\n------\n\na jitter algorithm can be supplied with the ``jitter`` keyword arg to\neither of the backoff decorators. this argument should be a function\naccepting the original unadulterated backoff value and returning it's\njittered counterpart.\n\nas of version 1.2, the default jitter function ``backoff.full_jitter``\nimplements the 'full jitter' algorithm as defined in the aws\narchitecture blog's `exponential backoff and jitter\n<https://www.awsarchitectureblog.com/2015/03/backoff.html>`_ post.\nnote that with this algorithm, the time yielded by the wait generator\nis actually the *maximum* amount of time to wait.\n\nprevious versions of backoff defaulted to adding some random number of\nmilliseconds (up to 1s) to the raw sleep value. if desired, this\nbehavior is now available as ``backoff.random_jitter``.\n\nusing multiple decorators\n-------------------------\n\nthe backoff decorators may also be combined to specify different\nbackoff behavior for different cases:\n\n.. code-block:: python\n\n    @backoff.on_predicate(backoff.fibo, max_value=13)\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.httperror,\n                          max_time=60)\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.timeout,\n                          max_time=300)\n    def poll_for_message(queue):\n        return queue.get()\n\n\nruntime configuration\n---------------------\n\nthe decorator functions ``on_exception`` and ``on_predicate`` are\ngenerally evaluated at import time. this is fine when the keyword args\nare passed as constant values, but suppose we want to consult a\ndictionary with configuration options that only become available at\nruntime. the relevant values are not available at import time. instead,\ndecorator functions can be passed callables which are evaluated at\nruntime to obtain the value:\n\n.. code-block:: python\n\n    def lookup_max_time():\n        # pretend we have a global reference to 'app' here\n        # and that it has a dictionary-like 'config' property\n        return app.config[\"backoff_max_time\"]\n\n    @backoff.on_exception(backoff.expo,\n                          valueerror,\n                          max_time=lookup_max_time)\n\nevent handlers\n--------------\n\nboth backoff decorators optionally accept event handler functions\nusing the keyword arguments ``on_success``, ``on_backoff``, and ``on_giveup``.\nthis may be useful in reporting statistics or performing other custom\nlogging.\n\nhandlers must be callables with a unary signature accepting a dict\nargument. this dict contains the details of the invocation. valid keys\ninclude:\n\n* *target*: reference to the function or method being invoked\n* *args*: positional arguments to func\n* *kwargs*: keyword arguments to func\n* *tries*: number of invocation tries so far\n* *elapsed*: elapsed time in seconds so far\n* *wait*: seconds to wait (``on_backoff`` handler only)\n* *value*: value triggering backoff (``on_predicate`` decorator only)\n\na handler which prints the details of the backoff event could be\nimplemented like so:\n\n.. code-block:: python\n\n    def backoff_hdlr(details):\n        print (\"backing off {wait:0.1f} seconds after {tries} tries \"\n               \"calling function {target} with args {args} and kwargs \"\n               \"{kwargs}\".format(**details))\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception,\n                          on_backoff=backoff_hdlr)\n    def get_url(url):\n        return requests.get(url)\n\n**multiple handlers per event type**\n\nin all cases, iterables of handler functions are also accepted, which\nare called in turn. for example, you might provide a simple list of\nhandler functions as the value of the ``on_backoff`` keyword arg:\n\n.. code-block:: python\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception,\n                          on_backoff=[backoff_hdlr1, backoff_hdlr2])\n    def get_url(url):\n        return requests.get(url)\n\n**getting exception info**\n\nin the case of the ``on_exception`` decorator, all ``on_backoff`` and\n``on_giveup`` handlers are called from within the except block for the\nexception being handled. therefore exception info is available to the\nhandler functions via the python standard library, specifically\n``sys.exc_info()`` or the ``traceback`` module. the exception is also\navailable at the *exception* key in the `details` dict passed to the\nhandlers.\n\nasynchronous code\n-----------------\n\nbackoff supports asynchronous execution in python 3.5 and above.\n\nto use backoff in asynchronous code based on\n`asyncio <https://docs.python.org/3/library/asyncio.html>`__\nyou simply need to apply ``backoff.on_exception`` or ``backoff.on_predicate``\nto coroutines.\nyou can also use coroutines for the ``on_success``, ``on_backoff``, and\n``on_giveup`` event handlers, with the interface otherwise being identical.\n\nthe following examples use `aiohttp <https://aiohttp.readthedocs.io/>`__\nasynchronous http client/server library.\n\n.. code-block:: python\n\n    @backoff.on_exception(backoff.expo, aiohttp.clienterror, max_time=60)\n    async def get_url(url):\n        async with aiohttp.clientsession(raise_for_status=true) as session:\n            async with session.get(url) as response:\n                return await response.text()\n\nlogging configuration\n---------------------\n\nby default, backoff and retry attempts are logged to the 'backoff'\nlogger. by default, this logger is configured with a nullhandler, so\nthere will be nothing output unless you configure a handler.\nprogrammatically, this might be accomplished with something as simple\nas:\n\n.. code-block:: python\n\n    logging.getlogger('backoff').addhandler(logging.streamhandler())\n\nthe default logging level is info, which corresponds to logging\nanytime a retry event occurs. if you would instead like to log\nonly when a giveup event occurs, set the logger level to error.\n\n.. code-block:: python\n\n    logging.getlogger('backoff').setlevel(logging.error)\n\nit is also possible to specify an alternate logger with the ``logger``\nkeyword argument.  if a string value is specified the logger will be\nlooked up by name.\n\n.. code-block:: python\n\n   @backoff.on_exception(backoff.expo,\n                         requests.exceptions.requestexception,\n\t\t\t logger='my_logger')\n   # ...\n\nit is also supported to specify a logger (or loggeradapter) object\ndirectly.\n\n.. code-block:: python\n\n    my_logger = logging.getlogger('my_logger')\n    my_handler = logging.streamhandler()\n    my_logger.addhandler(my_handler)\n    my_logger.setlevel(logging.error)\n\n    @backoff.on_exception(backoff.expo,\n                          requests.exceptions.requestexception,\n\t\t\t  logger=my_logger)\n    # ...\n\ndefault logging can be disabled all together by specifying\n``logger=none``. in this case, if desired alternative logging behavior\ncould be defined by using custom event handlers.\n",
  "docs_url": null,
  "keywords": "retry,backoff,decorators",
  "license": "mit",
  "name": "backoff",
  "package_url": "https://pypi.org/project/backoff/",
  "project_url": "https://pypi.org/project/backoff/",
  "project_urls": {
    "Homepage": "https://github.com/litl/backoff",
    "Repository": "https://github.com/litl/backoff"
  },
  "release_url": "https://pypi.org/project/backoff/2.2.1/",
  "requires_dist": [],
  "requires_python": ">=3.7,<4.0",
  "summary": "function decoration for backoff and retry",
  "version": "2.2.1",
  "releases": [],
  "developers": [
    "bob_green",
    "rgreen@aquent.com"
  ],
  "kwds": "on_backoff backoff status_code backoff_hdlr2 backoff_hdlr1",
  "license_kwds": "mit",
  "libtype": "pypi",
  "id": "pypi_backoff",
  "homepage": "https://github.com/litl/backoff",
  "release_count": 37,
  "dependency_ids": []
}