{
  "classifiers": [
    "development status :: 5 - production/stable",
    "framework :: asyncio",
    "intended audience :: developers",
    "license :: osi approved :: bsd license",
    "programming language :: python :: 3 :: only",
    "programming language :: python :: 3.10",
    "programming language :: python :: 3.11",
    "programming language :: python :: 3.12",
    "programming language :: python :: 3.5",
    "programming language :: python :: 3.6",
    "programming language :: python :: 3.7",
    "programming language :: python :: 3.8",
    "programming language :: python :: 3.9"
  ],
  "description": "|build| |status| |pypiversion| |license| |downloads|\n\nintroduction\n------------\n\nby design asyncio `does not allow <https://bugs.python.org/issue22239>`_\nits event loop to be nested. this presents a practical problem:\nwhen in an environment where the event loop is\nalready running it's impossible to run tasks and wait\nfor the result. trying to do so will give the error\n\"``runtimeerror: this event loop is already running``\".\n\nthe issue pops up in various environments, such as web servers,\ngui applications and in jupyter notebooks.\n\nthis module patches asyncio to allow nested use of ``asyncio.run`` and\n``loop.run_until_complete``.\n\ninstallation\n------------\n\n.. code-block::\n\n    pip3 install nest_asyncio\n\npython 3.5 or higher is required.\n\nusage\n-----\n\n.. code-block:: python\n\n    import nest_asyncio\n    nest_asyncio.apply()\n\noptionally the specific loop that needs patching can be given\nas argument to ``apply``, otherwise the current event loop is used.\nan event loop can be patched whether it is already running\nor not. only event loops from asyncio can be patched;\nloops from other projects, such as uvloop or quamash,\ngenerally can't be patched.\n\n\n.. |build| image:: https://github.com/erdewit/nest_asyncio/workflows/test/badge.svg?branche=master\n   :alt: build\n   :target: https://github.com/erdewit/nest_asyncio/actions\n\n.. |pypiversion| image:: https://img.shields.io/pypi/v/nest_asyncio.svg\n   :alt: pypi\n   :target: https://pypi.python.org/pypi/nest_asyncio\n\n.. |status| image:: https://img.shields.io/badge/status-stable-green.svg\n   :alt:\n\n.. |license| image:: https://img.shields.io/badge/license-bsd-blue.svg\n   :alt:\n\n.. |downloads| image:: https://static.pepy.tech/badge/nest-asyncio/month\n   :alt: number of downloads\n   :target: https://pepy.tech/project/nest-asyncio\n\n",
  "docs_url": null,
  "keywords": "asyncio,nested,eventloop",
  "license": "bsd",
  "name": "nest-asyncio",
  "package_url": "https://pypi.org/project/nest-asyncio/",
  "project_url": "https://pypi.org/project/nest-asyncio/",
  "project_urls": {
    "Homepage": "https://github.com/erdewit/nest_asyncio"
  },
  "release_url": "https://pypi.org/project/nest-asyncio/1.5.8/",
  "requires_dist": [],
  "requires_python": ">=3.5",
  "summary": "patch asyncio to allow nested event loops",
  "version": "1.5.8",
  "releases": [],
  "developers": [
    "ewald.de.wit@gmail.com",
    "ewald_r"
  ],
  "kwds": "nest_asyncio asyncio runtimeerror run_until_complete jupyter",
  "license_kwds": "bsd",
  "libtype": "pypi",
  "id": "pypi_nest_asyncio",
  "homepage": "https://github.com/erdewit/nest_asyncio",
  "release_count": 34,
  "dependency_ids": []
}